export const env = {
	SUPABASE_PROJECT_URL: import.meta.env.VITE_SUPABASE_PROJECT_URL,
	SUPABASE_API_KEY: import.meta.env.VITE_SUPABASE_API_KEY,
	OPENAI_API_KEY: import.meta.env.VITE_OPENAI_API_KEY,
	VITE_WEB_DOMAIN: import.meta.env.VITE_WEB_DOMAIN,
	VITE_STRIPE_MONTHLY_LINK: import.meta.env.VITE_STRIPE_MONTHLY_LINK,
	VITE_STRIPE_PUBLISHABLE_KEY: import.meta.env.VITE_STRIPE_PUBLISHABLE_KEY,
	VITE_STRIPE_SECRET_KEY: import.meta.env.VITE_STRIPE_SECRET_KEY,
	VITE_CAL_API_URL: import.meta.env.VITE_CAL_API_URL,
	VITE_CAL_CLIENT_ID: import.meta.env.VITE_CAL_CLIENT_ID,
	VITE_CAL_CLIENT_SECRET: import.meta.env.VITE_CAL_CLIENT_SECRET,
};
